### ISSUE TITLE
Update number of dogs in the world fact

### ISSUE THREAD

**Issue by busches** [kinduff/dogapi.dog#17]
**Describe the bug**
This fact is present in the API:
`There are about 400 million dogs in the world.`

Quite a few sources say there are now 900 million dogs in the world: 
- https://petkeen.com/how-many-dogs-are-there-statistics/
- https://a-z-animals.com/blog/how-many-dogs-are-in-the-world/
- https://www.worldatlas.com/articles/how-many-dogs-are-there-in-the-world.html

**To Reproduce**
I got this via the random API and don't have more details to share :)

**Expected behavior**
Update the fact to be `There are about 900 million dogs in the world.`

Thanks for this lovely API!

**Comment by kinduff** [comment]
Thanks for your contribution! The fact has been updated :+1:
